Product_Name:
    css: 'h1.a-size-large span.a-size-large'
    xpath: null
    type: Text
Brand:
    css: 'div#bylineInfo_feature_div.celwidget a.a-link-normal'
    xpath: null
    type: Text
Category:
    css: 'li:nth-of-type(1) span.a-list-item a.a-link-normal'
    xpath: null
    type: Text
Sub_Category:
    css: 'div.a-subheader li:nth-of-type(3) a.a-link-normal'
    xpath: null
    type: Text
Price:
    css: 'td.a-span12 span.a-size-medium'
    xpath: null
    type: Text
MRP:
    css: span.priceBlockStrikePriceString
    xpath: null
    type: Text
Return_Policy:
    css: 'span.a-declarative a.a-size-small'
    xpath: null
    type: Text
Seller_URL:
    css: 'a#sellerProfileTriggerId'
    xpath: null
    type: Link
Warranty:
    css: 'div#WARRANTY.a-column a.a-size-small'
    xpath: null
    type: Text
COD:
    css: 'div#PAY_ON_DELIVERY.a-column a.a-size-small'
    xpath: null
    type: Text
Fullfiled_by_Amazon:
    css: 'a#SSOFpopoverLink'
    xpath: null
    type: Text
All_Reviews_URL:
    css: 'div.a-row a.a-link-emphasis'
    xpath: null
    type: Link
